spring:
  profiles:
    active: dev
  datasource: #数据库链接相关配置
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${db.host}:${db.port:3306}/${db.database}?characterEncoding=utf-8
      username: ${db.username}
      password: ${db.password}
      db-type: com.alibaba.druid.pool.DruidDataSource
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      testWhileIdle: true
      testOnBorrow: true
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      filter:
        wall:
          config:
            show-allow: true

bot:
  admin: ${administrator}


